# Generated by Django 3.0.4 on 2020-03-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0003_auto_20200218_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='microchipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpref',
            name='microchipped',
            field=models.CharField(default='u', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
