# Generated by Django 3.0.4 on 2020-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20200328_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdog',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
